import express from "express";
import { healthCheck, ping } from "../health.js";
import authenticationRouter from "./authentication.route.js";
import { sanitizeBodyMiddleware } from "../middleware/validation.js";
import userRoute from "./user.route.js";
import stationRouter from "./station.route.js";
import OrderRouter from "./order.route.js";
import WebHookRouter from "./webhook.route.js";
import transactionRouter from "./transaction.route.js";
import agentRouter from "./agent.route.js";

const router = express.Router();
router.use(sanitizeBodyMiddleware);
router.get("/health", healthCheck);
router.get("/ping", ping);
router.use("/auth", authenticationRouter);
router.use("/users", userRoute);
router.use("/stations", stationRouter);
router.use("/orders", OrderRouter);
router.use("/transactions", transactionRouter);
router.use("/agents", agentRouter);
router.use("/webhooks", WebHookRouter);
export default router;
