export enum Permission {
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",
  USER_SUSPEND = "USER_SUSPEND",

  ROLE_CREATE = "ROLE_CREATE",
  ROLE_READ = "ROLE_READ",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",
  ROLE_ASSIGN = "ROLE_ASSIGN",

  STATION_CREATE = "STATION_CREATE",
  STATION_READ = "STATION_READ",
  STATION_UPDATE = "STATION_UPDATE",
  STATION_DELETE = "STATION_DELETE",

  ORDER_CREATE = "ORDER_CREATE",
  ORDER_READ = "ORDER_READ",
  ORDER_UPDATE = "ORDER_UPDATE",
  ORDER_CANCEL = "ORDER_CANCEL",
  ORDER_APPROVE = "ORDER_APPROVE",

  PAYMENT_READ = "PAYMENT_READ",
  PAYMENT_VERIFY = "PAYMENT_VERIFY",
  PAYMENT_REFUND = "PAYMENT_REFUND",

  DASHBOARD_READ = "DASHBOARD_READ",

  SETTINGS_UPDATE = "SETTINGS_UPDATE",

  TRANSACTION_READ = "TRANSACTION_READ",
}
