import env from "./index.js";

interface Config {
  NODE_ENV: "development" | "production" | "test";
  PORT: number;
  DATABASE_URL: string;
  JWT_SECRET: string;
  LOG_LEVEL: "debug" | "info" | "warn" | "error";
  CORS_ORIGIN: string;
  SERVO_SESSION_ACCESS_TOKEN_EXPIRES?: string;
  SERVO_SESSION_REFRESH_TOKEN_EXPIRES?: string;
  SERVO_SESSION_ACCESS_TOKEN_NAME: string;
  SERVO_SESSION_REFRESH_TOKEN_NAME: string;
  CLOUD_NAME: string;
  CLOUDINARY_API_KEY: string;
  CLOUDINARY_SECRET_KEY: string;
  ENCRYPTION_KEY: string;
  PAYSTACK_SECRET_KEY: string;
  PAYSTACK_BASE_URL: string;
  FLUTTERWAVE_SECRET_KEY: string;
  FLUTTERWAVE_BASE_URL: string;
  FLUTTERWAVE_SECRET_HASH: string;
  EMAIL_HOST: string;
  EMAIL_USER: string;
  EMAIL_PASS: string;
  EMAIL_PORT: number;
  EMAIL_SERVICE: string;

  RESEND_API_KEY: string;
  RESEND_USER: string;
  OTP_HMAC_SECRET: string;
  DEFAULT_AGENT_PASSWORD: string;
  PAYMENT_REDIRECT_URL: string;
  seed: {
    adminPassword: string;
    superAdminPassword: string;
    agentPassword?: string;
    customerPassword?: string;
  };
}

export const config: Config = {
  NODE_ENV: env.NODE_ENV,
  PORT: env.PORT,
  DATABASE_URL: env.DATABASE_URL,
  JWT_SECRET: env.JWT_SECRET,
  LOG_LEVEL: env.LOG_LEVEL,
  CORS_ORIGIN: env.CORS_ORIGIN,
  SERVO_SESSION_ACCESS_TOKEN_EXPIRES: env.SERVO_SESSION_ACCESS_TOKEN_EXPIRES,
  SERVO_SESSION_REFRESH_TOKEN_EXPIRES: env.SERVO_SESSION_REFRESH_TOKEN_EXPIRES,
  SERVO_SESSION_ACCESS_TOKEN_NAME: env.SERVO_SESSION_ACCESS_TOKEN_NAME,
  SERVO_SESSION_REFRESH_TOKEN_NAME: env.SERVO_SESSION_REFRESH_TOKEN_NAME,
  CLOUD_NAME: env.CLOUD_NAME,
  CLOUDINARY_API_KEY: env.CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_KEY: env.CLOUDINARY_SECRET_KEY,
  ENCRYPTION_KEY: env.ENCRYPTION_KEY,
  PAYSTACK_SECRET_KEY: env.PAYSTACK_SECRET_KEY,
  PAYSTACK_BASE_URL: env.PAYSTACK_BASE_URL,
  FLUTTERWAVE_SECRET_HASH: env.FLUTTERWAVE_SECRET_HASH,
  FLUTTERWAVE_SECRET_KEY: env.FLUTTERWAVE_SECRET_KEY,
  FLUTTERWAVE_BASE_URL: env.FLUTTERWAVE_BASE_URL,
  seed: {
    adminPassword: env.ADMIN_PASSWORD,
    superAdminPassword: env.SUPER_ADMIN_PASSWORD,
    agentPassword: env.AGENT_PASSWORD,
    customerPassword: env.CUSTOMER_PASSWORD,
  },
  EMAIL_HOST: env.EMAIL_HOST,
  EMAIL_USER: env.EMAIL_USER,
  EMAIL_PASS: env.EMAIL_PASS,
  EMAIL_PORT: Number(env.EMAIL_PORT),
  EMAIL_SERVICE: env.EMAIL_SERVICE,
  RESEND_API_KEY: env.RESEND_API_KEY,
  RESEND_USER: env.RESEND_USER,
  OTP_HMAC_SECRET: env.OTP_HMAC_SECRET,
  DEFAULT_AGENT_PASSWORD: env.DEFAULT_AGENT_PASSWORD,
  PAYMENT_REDIRECT_URL: env.PAYMENT_REDIRECT_URL,
};

export type { Config };
export default config;
